apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - cert-manager.yml
  - external-secrets.yml
  # - ingress-nginx.yml
  # - kafka.yml
  # - kube-prometheus-stack
  # - loki-stack
